const pizzaCondimenti = [
  '*Formaggio 🧀*',
  '*Salsa 🍅*',
  '*Wurstel 🍖*',
  '*Patatine 🍟*',
  '*Salame 🍖*',
  '*Piccante 🔥*',
  '*Ananas 🍍*',
  '*Acciughe 🐟*',
  '*Mozzarella 🧀*',
  '*Pistacchio 🌰*',
  '*Bufala 🐃*',
  '*Mortadella 🍖*',
  '*Prosciutto 🍖*',
  '*Funghi 🍄*',
  '*Olive 🫒*',
  '*Capricciosa 🍕*',
  '*Gruyère 🧀*',
  '*Gombas 🍄*',
  '*Peperoni 🔥*',
  '*Prosciutto crudo 🍖*',
  '*Ricotta 🧀*',
  '*Spinaci 🥗*',
  '*Tonno 🐟*',
  '*Zucchini 🥒*',
  '*Carne 🍖*',
  '*Pollo 🍗*',
  '*Salsiccia 🍖*',
  '*Bacon 🍖*',
  '*Arugula 🥗*',
  '*Pomodoro 🍅*',
  '*Aglio 🧄*',
  '*Cipolla 🧅*',
  '*Mais 🌽*',
  '*Jalapeño 🔥*',
  '*Pine Nuts 🌰*',
  '*Prosciutto di Parma 🍖*',
  '*Soppressata 🍖*',
  '*Burrata 🧀*',
  '*Graciano 🧀*',
  '*Scamorza 🧀*',
  '*Asparagi 🥗*',
  '*Broccoli 🥗*',
  '*Cavolfiore 🥗*',
  '*Cavolo 🥗*',
  '*Feta 🧀*',
  '*Gualda 🧀*',
  '*Prosciutto affumicato 🍖*',
  '*Salsiccia di maiale 🍖*',
  '*Salsiccia di pollo 🍖*',
  '*Salsiccia di tacchino 🍖*',
  '*Salsiccia di vitello 🍖*',
  '*Salsiccia piccante 🔥*',
  '*Salsiccia vegetale 🍖*',
  '*Sottaceti 🥗*',
  '*Spezi 🧀*',
  '*Stracchino 🧀*',
  '*Tartufi 🌰*',
  '*Trippa 🍲*',
  '*Uova 🥚*',
  '*Vegan 🍖*',
  '*Vegetariano 🥗*',
  '*Zucca 🥔*',
  '*Melone 🍈*',
  '*Prosciutto di Milano 🍖*',
  '*Salsiccia di Napoli 🍖*',
  '*Cacciatore 🍖*',
  '*Pepperoni 🍖*',
  '*Chorizo 🍖*',
  '*Mortadella di Bologna 🍖*',
  '*Prosciutto di Toscana 🍖*',
  '*Salsiccia di Toscana 🍖*',
  '*Funghi porcini 🍄*',
  '*Funghi champignons 🍄*',
  '*Funghi shiitake 🍄*',
  '*Funghi oyster 🍄*',
  '*Funghi enoki 🍄*',
  '*Funghi crimini 🍄*',
  '*Funghi portobello 🍄*',
  '*Funghi morel 🍄*',
  '*Funghi chanterelle 🍄*',
  '*Funghi lobster 🍄*',
  '*Funghi maitake 🍄*',
  '*Funghi reishi 🍄*',
  '*Pomodoro cherry 🍅*',
  '*Pomodoro datterino 🍅*',
  '*Pomodoro cuore 🍅*',
  '*Pomodoro ciliegino 🍅*',
  '*Pomodoro grappolo 🍅*',
  '*Pomodoro insalata 🍅*',
  '*Pomodoro pachino 🍅*',
  '*Pomodoro pelato 🍅*',
  '*Pomodoro piccato 🍅*',
  '*Pomodoro ramato 🍅*',
  '*Pomodoro San Marzano 🍅*',
  '*Pomodoro tondo 🍅*',
  '*Aglio nero 🧄*',
  '*Aglio bianco 🧄*',
  '*Aglio rosso 🧄*',
  '*Aglio elefante 🧄*',
  '*Cipolla bianca 🧅*',
  '*Cipolla rossa 🧅*',
  '*Cipolla gialla 🧅*',
  '*Cipolla cipollina 🧅*',
  '*Cipolla tropea 🧅*',
  '*Peperoncino verde 🔥*',
  '*Peperoncino rosso 🔥*',
  '*Peperoncino giallo 🔥*',
  '*Peperoncino habanero 🔥*',
  '*Peperoncino jalapeño 🔥*',
  '*Peperoncino serrano 🔥*',
  '*Peperoncino thai 🔥*',
  '*Peperoncino calabrese 🔥*',
  '*Peperoncino diavolo 🔥*',
  '*Peperoncino peperoncino 🔥*',
  '*Peperoncino piccante 🔥*',
  '*Peperoncino rosso piccante 🔥*',
  '*Peperoncino verde piccante 🔥*',
  '*Peperoncino giallo piccante 🔥*',
];

const risposte = [
  'Pizza perfetta!',
  'Che schifo!',
  'Mi piace!',
  'Non mi piace!',
  'È troppo piccante!',
  'È troppo salata!',
  'È troppo dolce!',
  'È troppo secca!',
  'È troppo umida!',
  'È troppo buona!',
  'È troppo cattiva!',
  'Mi fa schifo!',
  'Mi fa ridere!',
  'Mi fa piangere!',
  'Mi fa arrabbiare!',
  'Mi fa felice!',
  'Mi fa triste!',
  'Mi fa paura!',
  'Mi fa sorpresa!',
  'Mi fa disgusto!',
  'Mi fa noia!',
  'Mi fa dormire!',
  'Mi fa svegliare!',
  'Mi fa ballare!',
  'Mi fa cantare!',
  'Mi fa suonare!',
  'Mi fa scrivere!',
  'Mi fa leggere!',
  'Mi fa pensare!',
  'Mi fa sognare!',
  'Mi fa volare!',
  'Mi fa cadere!',
  'Mi fa correre!',
  'Mi fa fermare!',
  'Mi fa iniziare!',
  'Mi fa finire!',
];

const playAgainButtons = () => [{ name: 'quick_reply', buttonParamsJson: JSON.stringify({ display_text: 'Ordina un\'altra pizza! 🍕', id: `.pizza` }) }];

let handler = async (m, { conn, args }) => {
  let frasi = [
    `🍕 *Scegli i condimenti per la tua pizza!*`,
    `🔥 *Personalizza la tua pizza!*`,
    `🌟 *Crea la tua pizza ideale!*`,
    `🧂 *Scegli i tuoi condimenti preferiti!*`,
  ];

  if (global.pizzaGame?.[m.chat]) {
    return m.reply('⚠️ *C\'è già una partita attiva in questo gruppo!*');
  }

  const cooldownKey = `pizza_${m.chat}`;
  const lastGame = global.cooldowns?.[cooldownKey] || 0;
  const now = Date.now();
  const cooldownTime = 5000;
  if (now - lastGame < cooldownTime) {
    const remainingTime = Math.ceil((cooldownTime - (now - lastGame)) / 1000);
    return m.reply(`⏳ *Aspetta ancora ${remainingTime} secondi prima di avviare un nuovo gioco!*`);
  }

  global.cooldowns = global.cooldowns || {};
  global.cooldowns[cooldownKey] = now;

  let frase = frasi[Math.floor(Math.random() * frasi.length)];
  let messaggio = '*Scegli i condimenti per la tua pizza:*' + '\n\n';
  pizzaCondimenti.forEach((condimento, index) => {
    messaggio += `${index + 1}. ${condimento}\n`;
  });
  messaggio += '\n*Rispondi con i numeri dei condimenti separati da virgola (es. 1, 2, 3)*\n*Scrivi "fine" per terminare la tua pizza*';

  try {
    let msg = await conn.sendMessage(m.chat, { text: messaggio, footer: '🍕 𝖇𝖑𝖔𝖔𝖉𝖇𝖔𝖙 🍕' }, { quoted: m });
    global.pizzaGame =